# Generated by Django 4.0 on 2021-12-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del autor')),
                ('apellido', models.CharField(max_length=255, verbose_name='Apellido del autor')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook del autor')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Pagina web del autor')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico del autor')),
                ('estado', models.BooleanField(default=True, verbose_name='Autor activo/Autor no activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la categoria')),
                ('estado', models.BooleanField(default=True, verbose_name='Categoria activada/Categoria no activada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
