# Generated by Django 4.0 on 2021-12-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categorias_fecha_modificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='fecha_modificacion',
        ),
        migrations.AddField(
            model_name='post',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de modificacion'),
        ),
    ]
