# Generated by Django 4.0 on 2021-12-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_autor_id_alter_categorias_id_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='imagen',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
