# Generated by Django 4.0 on 2021-12-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
