# Generated by Django 4.0 on 2021-12-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comentarios_autor_alter_post_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='comentario_aprobado',
        ),
    ]
