# Generated by Django 4.0 on 2021-12-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_comentarios_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default=False, max_length=90, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='escritor',
            field=models.BooleanField(default=False, verbose_name='Es escritor/No es escritor'),
        ),
    ]
