# Generated by Django 4.0 on 2022-01-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_usuario_email_usuario_escritor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='escritor',
            field=models.BooleanField(default=True, verbose_name='Es escritor/No es escritor'),
        ),
    ]
