# Generated by Django 4.0 on 2022-01-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_usuario_escritor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='escritor',
            field=models.BooleanField(verbose_name='Es escritor/No es escritor'),
        ),
    ]
