# Generated by Django 4.0 on 2022-01-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_perfil_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='escritor',
            field=models.BooleanField(default=False, verbose_name='Es escritor/No es escritor'),
        ),
    ]
