# Generated by Django 4.0 on 2022-01-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_perfil_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
    ]
